#./exe/test01:./source/main.cpp
#	g++ -g -O2 -pthread -march=native ./source/main.cpp -o ./exe/test01 -lntl -lgmp -lm

#./exe/testcode:./source/testcode.cpp
#	g++ -g -O2 -pthread -march=native ./source/testcode.cpp -o ./exe/testcode -lntl -lgmp -lm

./exe/Enc_code:./source/Multi_PSI.cpp
	g++ -g -O2 -pthread -march=native ./source/Multi_PSI.cpp -o ./exe/Multi_PSI -lntl -lgmp -lm


.PHONY:clean
clean:
	@echo "=======clean project========"
	@echo "=======clean completed======"