#./exe/test01:./source/main.cpp
#	g++ -g -O2 -pthread -march=native ./source/main.cpp -o ./exe/test01 -lntl -lgmp -lm

#./exe/testcode:./source/testcode.cpp
#	g++ -g -O2 -pthread -march=native ./source/testcode.cpp -o ./exe/testcode -lntl -lgmp -lm

#./exe/Enc_code:./source/Enc_code.cpp
#	g++ -g -O2 -pthread -march=native ./source/Enc_code.cpp -o ./exe/Enc_code -lntl -lgmp -lm

./exe/Get_LE_Number:./source/Get_LE_Number.cpp
	g++ -g -O2 -pthread -march=native ./source/Get_LE_Number.cpp -o ./exe/Get_LE_Number -lntl -lgmp -lm


.PHONY:clean
clean:
	@echo "=======clean project========"
	@echo "=======clean completed======"